# Generated by Django 4.2.24 on 2025-10-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('description', models.TextField(verbose_name='설명')),
                ('start_time', models.DateTimeField(verbose_name='시작 시간')),
                ('end_time', models.DateTimeField(verbose_name='종료 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
            ],
            options={
                'verbose_name': '캘린더 이벤트',
                'verbose_name_plural': '캘린더 이벤트 목록',
                'db_table': 'calendar_event',
            },
        ),
        migrations.CreateModel(
            name='ChannelMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '채널 멤버',
                'verbose_name_plural': '채널 멤버 목록',
                'db_table': 'channel_member',
            },
        ),
        migrations.CreateModel(
            name='CommunityBoard',
            fields=[
                ('board_id', models.AutoField(primary_key=True, serialize=False)),
                ('board_title', models.CharField(max_length=100, verbose_name='게시판 제목')),
                ('board_type', models.CharField(max_length=20, verbose_name='게시판 유형')),
            ],
            options={
                'verbose_name': '커뮤니티 게시판',
                'verbose_name_plural': '커뮤니티 게시판 목록',
                'db_table': 'community_board',
            },
        ),
        migrations.CreateModel(
            name='CommunityComment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_content', models.TextField(verbose_name='댓글 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
            ],
            options={
                'verbose_name': '커뮤니티 댓글',
                'verbose_name_plural': '커뮤니티 댓글 목록',
                'db_table': 'community_comment',
            },
        ),
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_title', models.CharField(max_length=100, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('open', models.BooleanField(default=True, verbose_name='공개 여부')),
                ('view', models.IntegerField(default=0, verbose_name='조회수')),
            ],
            options={
                'verbose_name': '커뮤니티 게시글',
                'verbose_name_plural': '커뮤니티 게시글 목록',
                'db_table': 'community_post',
            },
        ),
        migrations.CreateModel(
            name='MeetingRequest',
            fields=[
                ('meeting_id', models.AutoField(primary_key=True, serialize=False)),
                ('meeting_time', models.DateTimeField(verbose_name='상담 요청 시간')),
                ('message', models.TextField(verbose_name='메시지 내용')),
                ('is_read', models.BooleanField(default=False, verbose_name='읽음 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
            ],
            options={
                'verbose_name': '상담 요청',
                'verbose_name_plural': '상담 요청 목록',
                'db_table': 'meeting_request',
            },
        ),
        migrations.CreateModel(
            name='MessengerChannel',
            fields=[
                ('channel_id', models.AutoField(primary_key=True, serialize=False)),
                ('channel_name', models.CharField(max_length=100, verbose_name='채널명')),
                ('channel_type', models.CharField(max_length=20, verbose_name='채널 유형')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
            ],
            options={
                'verbose_name': '메신저 채널',
                'verbose_name_plural': '메신저 채널 목록',
                'db_table': 'messenger_channel',
            },
        ),
        migrations.CreateModel(
            name='MessengerMessage',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='내용')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='전송 일시')),
                ('is_read', models.BooleanField(default=False, verbose_name='읽음 여부')),
            ],
            options={
                'verbose_name': '메신저 메시지',
                'verbose_name_plural': '메신저 메시지 목록',
                'db_table': 'messenger_messages',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_type', models.CharField(max_length=30, verbose_name='알림 유형')),
                ('message', models.TextField(verbose_name='메시지')),
                ('is_read', models.BooleanField(default=False, verbose_name='읽음 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
            ],
            options={
                'verbose_name': '알림',
                'verbose_name_plural': '알림 목록',
                'db_table': 'notification',
            },
        ),
        migrations.CreateModel(
            name='RequestClass',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_type', models.CharField(max_length=10, verbose_name='요청 유형')),
                ('requested_start_time', models.DateTimeField(verbose_name='요청 시작 시간')),
                ('requested_end_time', models.DateTimeField(verbose_name='요청 종료 시간')),
                ('approved', models.CharField(choices=[('승인', '승인'), ('거절', '거절'), ('보류', '보류')], default='보류', max_length=20, verbose_name='승인 상태')),
                ('is_read', models.BooleanField(default=False, verbose_name='수신 확인')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
            ],
            options={
                'verbose_name': '강의 신청/수정 요청',
                'verbose_name_plural': '강의 신청/수정 요청 목록',
                'db_table': 'request_class',
            },
        ),
    ]
