# Generated by Django 4.2.24 on 2025-10-20 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestclass',
            name='manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_requests', to=settings.AUTH_USER_MODEL, verbose_name='승인 매니저'),
        ),
        migrations.AddField(
            model_name='requestclass',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='요청자'),
        ),
        migrations.AddField(
            model_name='notification',
            name='class_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.classcomment', verbose_name='강의 댓글 참조'),
        ),
        migrations.AddField(
            model_name='notification',
            name='class_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.requestclass', verbose_name='강의 요청 참조'),
        ),
        migrations.AddField(
            model_name='notification',
            name='community_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.communitycomment', verbose_name='커뮤니티 댓글 참조'),
        ),
        migrations.AddField(
            model_name='notification',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.calendarevent', verbose_name='이벤트 참조'),
        ),
        migrations.AddField(
            model_name='notification',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.meetingrequest', verbose_name='상담 요청 참조'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='수신 사용자'),
        ),
        migrations.AddField(
            model_name='messengermessage',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.messengerchannel', verbose_name='채널'),
        ),
        migrations.AddField(
            model_name='messengermessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='보낸 사람'),
        ),
        migrations.AddField(
            model_name='meetingrequest',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.messengerchannel', verbose_name='일정 조율 채널'),
        ),
        migrations.AddField(
            model_name='meetingrequest',
            name='instructor',
            field=models.ForeignKey(limit_choices_to={'role': 'instructor'}, on_delete=django.db.models.deletion.CASCADE, related_name='received_meetings', to=settings.AUTH_USER_MODEL, verbose_name='강사'),
        ),
        migrations.AddField(
            model_name='meetingrequest',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='requested_meetings', to=settings.AUTH_USER_MODEL, verbose_name='학생'),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.communityboard', verbose_name='게시판'),
        ),
        migrations.AddField(
            model_name='communitycomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
        migrations.AddField(
            model_name='communitycomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.communitypost', verbose_name='게시글'),
        ),
        migrations.AddField(
            model_name='channelmember',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.messengerchannel', verbose_name='채널'),
        ),
        migrations.AddField(
            model_name='channelmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='class_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.class', verbose_name='강의'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AlterUniqueTogether(
            name='channelmember',
            unique_together={('channel', 'user')},
        ),
    ]
