# Generated by Django 4.2.24 on 2025-10-20 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(max_length=30, verbose_name='이름')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='아이디(이메일)')),
                ('role', models.CharField(choices=[('student', '학생'), ('instructor', '강사'), ('manager', '매니저')], default='student', max_length=10, verbose_name='역할')),
                ('phone_number', models.CharField(default='010-0000-0000', max_length=15, unique=True, verbose_name='전화번호')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='주소')),
                ('birthday', models.DateTimeField(blank=True, null=True, verbose_name='생년월일')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='프로필 사진')),
                ('code', models.CharField(blank=True, max_length=15, null=True, verbose_name='기관 인증코드')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자 목록',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='DIMC',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('pdf_path', models.TextField(verbose_name='PDF 파일 경로')),
                ('D_score', models.IntegerField(verbose_name='D 점수')),
                ('I_score', models.IntegerField(verbose_name='I 점수')),
                ('M_score', models.IntegerField(verbose_name='M 점수')),
                ('C_score', models.IntegerField(verbose_name='C 점수')),
                ('result', models.TextField(verbose_name='테스트 결과')),
                ('tested_at', models.DateTimeField(auto_now_add=True, verbose_name='테스트 일시')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DIMC 테스트 결과',
                'verbose_name_plural': 'DIMC 테스트 결과 목록',
                'db_table': 'DIMC',
            },
        ),
    ]
