# Generated by Django 5.2.8 on 2025-11-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='010-0000-0000', max_length=15, null=True, unique=True, verbose_name='전화번호'),
        ),
    ]
