# Generated by Django 4.2.24 on 2025-10-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=100, verbose_name='강의명')),
            ],
            options={
                'verbose_name': '강의',
                'verbose_name_plural': '강의 목록',
                'db_table': 'class',
            },
        ),
        migrations.CreateModel(
            name='ClassBoard',
            fields=[
                ('board_id', models.AutoField(primary_key=True, serialize=False)),
                ('board_name', models.CharField(max_length=100, verbose_name='게시판 이름')),
                ('board_type', models.CharField(max_length=20, verbose_name='게시판 유형')),
            ],
            options={
                'verbose_name': '강의 게시판',
                'verbose_name_plural': '강의 게시판 목록',
                'db_table': 'class_board',
            },
        ),
        migrations.CreateModel(
            name='ClassComment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_content', models.TextField(verbose_name='댓글 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
            ],
            options={
                'verbose_name': '강의 댓글',
                'verbose_name_plural': '강의 댓글 목록',
                'db_table': 'class_comment',
            },
        ),
        migrations.CreateModel(
            name='ClassPost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('open', models.BooleanField(default=True, verbose_name='공개 여부')),
                ('view_count', models.IntegerField(default=0, verbose_name='조회수')),
            ],
            options={
                'verbose_name': '강의 게시글',
                'verbose_name_plural': '강의 게시글 목록',
                'db_table': 'class_post',
            },
        ),
        migrations.CreateModel(
            name='MaterialFile',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=100, verbose_name='파일명')),
                ('file_path', models.TextField(verbose_name='파일 경로')),
                ('file_size', models.IntegerField(verbose_name='파일 크기')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드 일시')),
            ],
            options={
                'verbose_name': '강의 자료 파일',
                'verbose_name_plural': '강의 자료 파일 목록',
                'db_table': 'material_file',
            },
        ),
        migrations.CreateModel(
            name='MyClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '수강 신청',
                'verbose_name_plural': '수강 신청 목록',
                'db_table': 'myclass',
            },
        ),
        migrations.CreateModel(
            name='MyClassStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0, verbose_name='진행도(%)')),
            ],
            options={
                'verbose_name': '수강 진행 상태',
                'verbose_name_plural': '수강 진행 상태 목록',
                'db_table': 'myclass_status',
            },
        ),
        migrations.CreateModel(
            name='SatisfactionSurvey',
            fields=[
                ('survey_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='설문조사 제목')),
                ('start_date', models.DateTimeField(verbose_name='강의평가 시작 기간')),
                ('end_date', models.DateTimeField(verbose_name='강의평가 종료 기간')),
            ],
            options={
                'verbose_name': '강의 만족도 조사',
                'verbose_name_plural': '강의 만족도 조사 목록',
                'db_table': 'satisfaction_survey',
            },
        ),
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer_value', models.TextField(max_length=255, verbose_name='응답값')),
            ],
            options={
                'verbose_name': '설문조사 응답',
                'verbose_name_plural': '설문조사 응답 목록',
                'db_table': 'survey_answer',
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=255, verbose_name='질문 내용')),
                ('question_type', models.CharField(max_length=20, verbose_name='질문 유형')),
                ('question_num', models.IntegerField(verbose_name='질문 번호')),
            ],
            options={
                'verbose_name': '설문조사 질문',
                'verbose_name_plural': '설문조사 질문 목록',
                'db_table': 'survey_question',
            },
        ),
        migrations.CreateModel(
            name='SurveySubmission',
            fields=[
                ('submission_id', models.AutoField(primary_key=True, serialize=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='제출 일시')),
            ],
            options={
                'verbose_name': '설문조사 제출',
                'verbose_name_plural': '설문조사 제출 목록',
                'db_table': 'survey_submission',
            },
        ),
    ]
