# Generated by Django 4.2.24 on 2025-10-20 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='surveysubmission',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='학생'),
        ),
        migrations.AddField(
            model_name='surveysubmission',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.satisfactionsurvey', verbose_name='설문조사'),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.satisfactionsurvey', verbose_name='설문조사'),
        ),
        migrations.AddField(
            model_name='surveyanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.surveyquestion', verbose_name='질문 ID'),
        ),
        migrations.AddField(
            model_name='surveyanswer',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.surveysubmission', verbose_name='제출 ID'),
        ),
        migrations.AddField(
            model_name='satisfactionsurvey',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.class', verbose_name='강의'),
        ),
        migrations.AddField(
            model_name='myclassstatus',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.class', verbose_name='강의'),
        ),
        migrations.AddField(
            model_name='myclassstatus',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='학생'),
        ),
        migrations.AddField(
            model_name='myclass',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.class', verbose_name='강의'),
        ),
        migrations.AddField(
            model_name='myclass',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='학생'),
        ),
        migrations.AddField(
            model_name='materialfile',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.classpost', verbose_name='게시글'),
        ),
        migrations.AddField(
            model_name='classpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
        migrations.AddField(
            model_name='classpost',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.classboard', verbose_name='게시판'),
        ),
        migrations.AddField(
            model_name='classcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
        migrations.AddField(
            model_name='classcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.classpost', verbose_name='게시글'),
        ),
        migrations.AddField(
            model_name='classboard',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.class', verbose_name='강의'),
        ),
        migrations.AddField(
            model_name='class',
            name='instructor',
            field=models.ForeignKey(limit_choices_to={'role': 'instructor'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='강사'),
        ),
        migrations.AlterUniqueTogether(
            name='surveysubmission',
            unique_together={('survey', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='surveyanswer',
            unique_together={('submission', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='myclassstatus',
            unique_together={('student', 'class_obj')},
        ),
        migrations.AlterUniqueTogether(
            name='myclass',
            unique_together={('class_obj', 'student')},
        ),
    ]
